export const ROUTES = Object.freeze({
  HOME: '/',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  LOGOUT: '/logout',
  ACTIVATE: '/activate',
  RECOVERY: '/recovery',
  RESET: '/reset',
  CLUB_ADD: '/club-add',
  CLUBS: '/clubs',
  PROFILE: '/profile',
  SEARCH: '/search',
  TEAMS: '/teams',
  GAMES: '/games',
  INVITATIONS: '/invitations',
})
